### ISSUE TITLE
ReceiverOptions parameter name mismatch

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot.Extensions.Polling#11]
There are several instances where parameter/property name does not match `ReceiverOptions` type:

- [ ] https://github.com/TelegramBots/Telegram.Bot.Extensions.Polling/blob/6df06b7346425b2c4176c36f84015fba97a2727b/src/Telegram.Bot.Extensions.Polling/Extensions/TelegramBotClientPollingExtensions.cs#L33
- [ ] https://github.com/TelegramBots/Telegram.Bot.Extensions.Polling/blob/6df06b7346425b2c4176c36f84015fba97a2727b/src/Telegram.Bot.Extensions.Polling/Extensions/TelegramBotClientPollingExtensions.cs#L61
- [ ] https://github.com/TelegramBots/Telegram.Bot.Extensions.Polling/blob/6df06b7346425b2c4176c36f84015fba97a2727b/src/Telegram.Bot.Extensions.Polling/DefaultUpdateReceiver.cs#L18
- [ ] https://github.com/TelegramBots/Telegram.Bot.Extensions.Polling/blob/6df06b7346425b2c4176c36f84015fba97a2727b/src/Telegram.Bot.Extensions.Polling/AsyncEnumerableReceivers/BlockingUpdateReceiver.cs#L20
- [ ] https://github.com/TelegramBots/Telegram.Bot.Extensions.Polling/blob/6df06b7346425b2c4176c36f84015fba97a2727b/src/Telegram.Bot.Extensions.Polling/AsyncEnumerableReceivers/BlockingUpdateReceiver.cs#L36
- [ ] https://github.com/TelegramBots/Telegram.Bot.Extensions.Polling/blob/6df06b7346425b2c4176c36f84015fba97a2727b/src/Telegram.Bot.Extensions.Polling/AsyncEnumerableReceivers/QueuedUpdateReceiver.cs#L23
- [ ] https://github.com/TelegramBots/Telegram.Bot.Extensions.Polling/blob/6df06b7346425b2c4176c36f84015fba97a2727b/src/Telegram.Bot.Extensions.Polling/AsyncEnumerableReceivers/QueuedUpdateReceiver.cs#L39

**Comment by tuscen** [comment]
Thanks for noticing, will fix this this week

**Comment by maxoncheeg** [comment]
Ошибка	CS0246	Не удалось найти тип или имя пространства имен "ReceiverOptions" (возможно, отсутствует директива using или ссылка на сборку).

**Comment by n08i40k** [comment]
> Ошибка CS0246 Не удалось найти тип или имя пространства имен "ReceiverOptions" (возможно, отсутствует директива using или ссылка на сборку).

прост установи более старую версию

**Comment by n08i40k** [comment]
> Ошибка CS0246 Не удалось найти тип или имя пространства имен "ReceiverOptions" (возможно, отсутствует директива using или ссылка на сборку).

Извиняюсь, ошибся, установи nuget пакет версии 1.0.0-alpha

**Comment by n08i40k** [comment]
![image](https://user-images.githubusercontent.com/55545594/130601210-32a8a743-4de6-4f58-aab6-b0e2f4943dbd.png)

**Comment by karb0f0s** [comment]
fixed in 6c20f21f6cde9af6f3eb993db5699303a9ce4388
