### ISSUE TITLE
Connection to database

### ISSUE THREAD

**Issue by ghost** [TelegramBots/Telegram.Bot.Extensions.Polling#22]
I have a problem when I try connect to database with telegramBot:

System.ObjectDisposedException: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'ApplicationContext'.

**Comment by tuscen** [comment]
If you have any question about the library please join our support group https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA.
