### ISSUE TITLE
Handling Concurrency Conflicts

### ISSUE THREAD

**Issue by DeveloperAzamat** [TelegramBots/Telegram.Bot.Extensions.Polling#30]
Hi everyone. I have one problem with **Handling Concurrency Conflicts**.
I have two project and they work parallel but i have that error: 
 
_Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded._ 

How can i solve this problem?

**Comment by karb0f0s** [comment]
This issue is not related in to this project. Please follow the issue template.
