### ISSUE TITLE
Update Streams are not supported in QueuedUpdateReceiver

### ISSUE THREAD

**Issue by jasursadikov** [TelegramBots/Telegram.Bot.Extensions.Polling#9]
```
CS8411
Asynchronous foreach statement cannot operate on variables of type 'QueuedUpdateReceiver'
because 'QueuedUpdateReceiver' does not contain a suitable public instance or extension definition 
for 'GetAsyncEnumerator'
```

I get this error when I try to use update streams as shown in an example in [README.md](https://github.com/TelegramBots/Telegram.Bot.Extensions.Polling/blob/master/README.md)

My project runs .NET 5, package version is latest atm (`0.2.0`)

**Comment by tuscen** [comment]
The readme is for a newer version that is not released yet.

**Comment by jasursadikov** [comment]
@tuscen why this is not mentioned? Telegram.Bot package documented really bad

**Comment by tuscen** [comment]
We dont't have enough people and time to write good documentation.

I've released the first alpha of the polling package. It should work as in the readme now.
